tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/services"

tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"

brew "bash-completion@2"
brew "brew-cask-completion"
brew "bats"
brew "coreutils"
brew "moreutils"
brew "findutils"
brew "ack"
brew "mas"
brew "ffmpeg"
brew "gnu-sed"
brew "grep"
brew "git"
brew "jq"
brew "httpie"
brew "imagemagick"
brew "fx"
brew "lynx"
brew "mackup"
brew "nano"
brew "openssh"
brew "pandoc"
brew "python"
brew "python3"
brew "ssh-copy-id"
brew "stow"
brew "tree"
brew "wget"
brew "tldr"
brew "wifi-password"
brew "yarn"
brew "yarn-completion"
brew "youtube-dl"

cask "alfred"
cask "enpass"
cask "rambox"
cask "gitkraken"
cask "webstorm"
cask "datagrip"
cask "robo-3t"
cask "aerial"
cask "deezer"
cask "dropbox"
cask "google-chrome"
cask "google-chrome-canary"
cask "firefox"
cask "homebrew/cask-versions/firefox-developer-edition"
cask "insomnia"
cask "postman"
cask "virtualbox"
cask "vscodium"
cask "vlc"
cask "cakebrew"
cask "dash"
cask "docker"
cask "https://raw.githubusercontent.com/popcorn-official/popcorn-desktop/development/casks/popcorn-time.rb"
cask "font-karla"
cask "font-mononoki"
cask "font-roboto"
cask "google-chrome"
cask "sublime-text"
cask "mamp"
cask "the-unarchiver"
cask "adapter"
cask "imageoptim"
cask "airflow"
cask "cryptomator"
cask "numi"
cask "adobe-acrobat-reader"
cask "microsoft-office"
cask "ngrok"
cask "sequel-pro"


# Quick Look Plugins (https://github.com/sindresorhus/quick-look-plugins)
cask "provisionql"
cask "qlcolorcode"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlstephen"
cask "qlvideo"
cask "quicklook-csv"
cask "quicklook-json"
cask "suspicious-package"
cask "webpquicklook"

mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Unsplash Wallpapers", id: 1284863847
mas "Amphetamine", id: 937984704
mas "Shazam", id: 897118787
mas "Xcode", id: 497799835

